package com.example.hw4

object SingerReponsitory {
    val singers = arrayListOf(
        Singer(0, "Mary J. Blige", "\"Anybody my age turning on MTV and seeing Annie Lennox sing 'Sweet Dreams' — that was enough right there,\" says Rob Thomas. \"There was something so soulful in the way she sang songs like 'Walking on Broken Glass.' \" Lennox combines a childhood love of Motown with an operatically powerful voice — crystalline in tone, yet sultry. She introduced R&B to New Wave with Eurythmics, and in her solo career, she invented a sort of New Age soul, based around shimmering synths, horn blasts and, most important, layer upon layer of that voice. \"Annie is amazingly versatile,\" says Thomas. \"She can sound like a beautiful angel — or she can make it sound like she's gargling glass. A great singer is somebody who makes you believe what they're saying, and you always believe Annie.\"", "https://media.glamour.com/photos/620a9419cded3ef698685714/master/w_2560%2Cc_limit/1370404189"),
        Singer(1, "Steven Tyler", "Bono said that when he first heard Morrissey singing the Smiths' acid-tongued \"Girlfriend in a Coma,\" \"I nearly crashed my car and ended up in a coma. He has that gift.\" An icon of New Wave from his days in the Smiths and in his solo career, Morrissey owns a voice that's mannered, ironic, even consciously feminine — his phrasing owes more to tuxedoed crooners than to any rock singers before him. But his rejection of convention is also why he redefined the sound of British rock for the past quarter-century. With his falsetto cries, rolled r's and warbling yodels, he pulled off lyrics few other singers could possibly have gotten away with, and he opened up possibilities for rockers who've followed him, from Oasis to Interpol.", "https://www.biography.com/.image/t_share/MTg1Njc5NjcxMjY5MDA5MDI0/gettyimages-1196636806.jpg"),
        Singer(2, "Stevie Nicks", "Jeff Tweedy, Lucinda Williams, John Hiatt\n" +
                "\n" +
                "There is something about Levon Helm's voice that is contained in all of our voices. It is ageless, timeless and has no race. He can sing with such depth and emotion, but he can also convey a good-old fun-time growl.", "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-134968-stevie-nicks.jpg?w=306"),
        Singer(3, "Joe Cocker", "Beginning with the Beatles and Simon and Garfunkel, every group for whom harmony singing is important owes a crucial debt to the Everly Brothers. Their hits in the Fifties and early Sixties seemed at once raw and pristine: When he first heard the Everlys, Art Garfunkel says, \"I learned that every syllable can shine. They were Kentucky guys with beautiful, perfect-pitch harmonies and great diction. All those vowels and consonants, those s's and t's, every one of them killed me.\" ", "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-134967-joe-cocker.jpg?w=306"),
        Singer(4, "B.B. King", "Because Solomon Burke never had a big crossover hit, \"the King of Rock and Soul\" is not as widely known as others from the golden age of soul music. But his dramatic, sonorous voice — seasoned by his days as a boy preacher — is unrivaled in its ability to move effortlessly between R&B, pop, country and gospel. ", "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-134967-joe-cocker.jpg?w=306"),
        Singer(5, "Patti LaBelle", "Willie Nelson's secret ingredient is his unconventional phrasing — something jazz trumpeter Wynton Marsalis has described as \"very unpredictable, but it comes out poetic and very logical.\" Dwight Yoakam calls Nelson \"the most avant-garde country singer of all time.\" ", "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-134965-patti-labelle.jpg?w=306"),
        Singer(6, "Karen Carpenter", "Don Henley got his famously rough voice from belting out R&B tunes at Texas college gigs in his early band the Speeds. \"The frat boys would all want James Brown, Wilson Pickett, Otis Redding music, which I had to learn,\" Henley said. \"I got hoarse singing that music four hours a night, trying to sound raspy until my voice blew out.\"", "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-134964-karen-carpenter.jpg?w=306"),
        Singer(7, "Annie Lennox", "Don Henley got his famously rough voice from belting out R&B tunes at Texas college gigs in his early band the Speeds. \"The frat boys would all want James Brown, Wilson Pickett, Otis Redding music, which I had to learn,\" Henley said. \"I got hoarse singing that music four hours a night, trying to sound raspy until my voice blew out.\"", "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-134963-annie-lennox.jpg?w=306"),
        Singer(8, "Mary J. Blige", "\"He is a pure and beautiful tenor voice, and there really is no one like him,\" says James Taylor about Art Garfunkel, whose singing blends lyricism with a remarkable ease of delivery. He brought sweetness and wonder to his classic harmonies with Paul Simon, a delicacy that defined those songs, and some of the hopes of the late Sixties. \"I'm looking for controlled beauty,\" he says, a standard he learned as a child from the likes of Italian opera star Enrico Caruso. ", "https://media.glamour.com/photos/620a9419cded3ef698685714/master/w_2560%2Cc_limit/1370404189"),
        Singer(9, "Steven Tyler", "\"You have to put something in it to make them move,\" said Sam Moore, half of the Sixties R&B duo Sam and Dave. Moore boasts a scratchy voice with incredible range — all honey-sweet soul and raw sexuality, gutbucket blues and gritty rock. He met fellow struggling club singer Dave Prater on the Miami R&B circuit in 1961;", "https://www.biography.com/.image/t_share/MTg1Njc5NjcxMjY5MDA5MDI0/gettyimages-1196636806.jpg"),
        Singer(10, "Stevie Nicks", "May 26th, 1948", "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-134968-stevie-nicks.jpg?w=306"),
        Singer(11, "Joe Cocker", "May 20th, 1944", "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-134967-joe-cocker.jpg?w=306"),
        Singer(12, "B.B. King", "September 16th, 1925", "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-134967-joe-cocker.jpg?w=306"),
        Singer(13, "Patti LaBelle", "May 24th, 1944", "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-134965-patti-labelle.jpg?w=306"),
        Singer(14, "Karen Carpenter", "March 2nd, 1950 (died February 4th, 1983)", "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-134964-karen-carpenter.jpg?w=306"),
        Singer(15, "Annie Lennox", "December 25th, 1954", "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-134963-annie-lennox.jpg?w=306"),
    )
}